# Generated by Django 3.1.4 on 2021-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('revenue', models.CharField(max_length=100)),
                ('sales', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('fba', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
