# Generated by Django 3.2.4 on 2021-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=5000)),
                ('brand', models.CharField(max_length=500)),
                ('categories', models.CharField(blank=True, max_length=5000, null=True)),
                ('price', models.FloatField()),
                ('sales', models.FloatField()),
                ('revenue', models.FloatField()),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-sales'],
            },
        ),
    ]
