# Generated by Django 3.1.4 on 2021-06-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probec_main', '0004_auto_20210628_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-sales']},
        ),
    ]
