# Generated by Django 3.1.4 on 2021-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probec_main', '0005_auto_20210628_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField()),
                ('asin', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=5000)),
                ('brand', models.CharField(max_length=500)),
                ('categories', models.CharField(max_length=5000)),
                ('price', models.FloatField()),
                ('sales', models.FloatField()),
                ('revenue', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-sales'],
            },
        ),
    ]
