# Generated by Django 3.1.4 on 2021-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probec_main', '0006_productsales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSales',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
